### ISSUE TITLE
Artifact will be too large

### ISSUE THREAD

**Issue by Gcenx** [GabLeRoux/macos-crossover-cloud-build#10]
https://github.com/GabLeRoux/macos-crossover-cloud-build/blob/1fed4eae316c289adb38712e4885f0f9c4aa85b2/.github/workflows/build.yml#L15-L18

Doing this will results in an almost 2GB  artifact, you’ll only want the wine files, after make run make install DESTROOT=“some other location”

Then tar and upload that only.

**Comment by GabLeRoux** [comment]
I think this is now outdated according to
https://github.com/GabLeRoux/macos-crossover-cloud-build/blob/2eb377feae550f452760ea4077a79b4ca9c5fd17/.github/workflows/build_monolithic.yml#L340-L344

and 

https://github.com/GabLeRoux/macos-crossover-cloud-build/blob/2eb377feae550f452760ea4077a79b4ca9c5fd17/.github/workflows/build_local.yml#L35-L39

Closing it for now, feel free to create a new issue if we need to do something about artifacts
