### ISSUE TITLE
Can we distribute free builds here?

### ISSUE THREAD

**Issue by GabLeRoux** [GabLeRoux/macos-crossover-cloud-build#2]
There is probably something tricky in providing the builds. I'm not sure if it can be distributed freely here. If you know the answer, let me know.

**Comment by Gcenx** [comment]
Your better contacting CodeWeavera via there support system if you want clarification.

I’ve been providing prebuilt packages for a while now and also provide a Winehq like package (of 19.0.2 currently as 20.0.x is unstable and refuses to run on 10.9 without patches), I’ve contacted CodeWeavers numerous times for assistance with weirdness or just asking to fix there source links and why DXVK/MoltenVK were missing for the initial 20.0.0 upload.

**Comment by GabLeRoux** [comment]
I sent them a message, I'll report here with the answer :)

**Comment by Gcenx** [comment]
It’s strange I’ve had responses to some of my tickets even very technical ones but not others.

I’m guessing as this one was more general they haven’t gotten around to it yet.

**Comment by GabLeRoux** [comment]
Oh, forgot to reply here, I received an answer on December 22nd and it seems positive:

> Each of those projects has it's own license; the main one, Wine, certainly allows you to redistribute binaries that you build from the source code.  The license files with precise details should be in each archive.

Might be better to give a look at these licenses. But no matter what happens, publishing the results here won't happen unless [#6](https://github.com/GabLeRoux/macos-crossover-cloud-build/issues/6) gets solved

**Comment by Gcenx** [comment]
I’d have been surprised if that wasn’t the response considering, there aware of my packages and were also aware of doh123 when she was still active.

Even when you resolve #6 there will be additional errors after this, might wanna hold off until CX21.

**Comment by GabLeRoux** [comment]
I'll be considering that the answer is yes we can according to answer I received here:  
https://github.com/GabLeRoux/macos-crossover-cloud-build/issues/2#issuecomment-763996321

Feel free to reopen or create a new issue if there is a license problem, but it looks like it is ok to have the artifacts as they are right now.
