### ISSUE TITLE
/dlls/bcrypt/macos.c:54:1: error: array size is negative

### ISSUE THREAD

**Issue by TroyWolbrink** [GabLeRoux/macos-crossover-cloud-build#21]
I'm trying to compile CrossOver 21.0 on a Mac 15.5.  I keep getting this error:

i686-w64-mingw32-gcc -c -o dlls/browseui/aclsource.cross.o /Users/troy/Desktop/macos-crossover-cloud-build/sources/wine/dlls/browseui/aclsource.c \
  -I dlls/browseui -I /Users/troy/Desktop/macos-crossover-cloud-build/sources/wine/dlls/browseui -I \
  include -I /Users/troy/Desktop/macos-crossover-cloud-build/sources/wine/include -I \
  /Users/troy/Desktop/macos-crossover-cloud-build/sources/wine/include/msvcrt -D__WINESRC__ -D_UCRT \
  -DWINE_CROSS_PE -Wall -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wabsolute-value \
  -fno-omit-frame-pointer -gdwarf-2 -gstrict-dwarf -g -O2
**/Users/troy/Desktop/macos-crossover-cloud-build/sources/wine/dlls/bcrypt/macos.c:54:1: _error_: array size is negative**
C_ASSERT( sizeof(struct key_data) <= sizeof(((struct key *)0)->private) );
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/troy/Desktop/macos-crossover-cloud-build/sources/wine/include/winnt.h:394:51: note: expanded from macro 'C_ASSERT'
#define C_ASSERT(e) extern void __C_ASSERT__(int [(e)?1:-1])
                                                  ^~~~~~~~
1 error generated.
make: *** [dlls/bcrypt/macos.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by TroyWolbrink** [comment]
I found the problem.  You have to run "**brew install gnutls**".  I guess your script is missing this prereq.

I'm able to compile CrossOver 21.0 using the cx-21.0 recent commits by https://github.com/dasmy 

Thanks for this project!

**Comment by Gcenx** [comment]
The #20 branch hasn’t been merged due to mostly my stubbornness with having things working cleanly.

Strange I’m sure the local build script did include gnutls, guess I’d missed that one prior sigh….

**Comment by TroyWolbrink** [comment]
By the way, I'm able to run my Windows application on this build of CX 21.0, and it's working beautifully on the machine I did the build on.  When I take the wine build from the "Uploads" folder and move it to another computer, it's not able to start up my application with wine, since it's missing FreeType (libfreetype).  I'm trying to come up with a self-contained build of CX 21.0 that has all the dependencies with it.  Do you have a script that shows how to grab all the dependencies?  Sorry if this is a newbie question.

**Comment by TroyWolbrink** [comment]
On the new computer, I ran "brew install freetype" and "brew install gnutls" and now my CX 21.0 instance (compiled from your script) is running very well.  I'll have to do more testing, but I think those are the only two libraries I must include with the wine archive in the "Uploads" directory.

**Comment by dasmy** [comment]
Sounds like we might need a github action CI job (I.e. on a blank machine using just the artifacts created) that runs some elementary tests on wine make sure it runs properly and/or document libraries that still need to packaged/installed manually.

@Gcenx: Do you know if there is some kind of runtime test suite for wine?

**Comment by Gcenx** [comment]
@TroyWolbrink just dropping in the libraries won't work due to the removal of `wine_dlopen` see [Bugzilla 49199](https://bugs.winehq.org/show_bug.cgi?id=49199)

@dasmy need to ensure the user installs the needed libraries on the system using Intel brew, there really isn't anything in the test suite aimed at macOS as there no macOS testbots unfortunately....
