### ISSUE TITLE
Compiler cannot create executables

### ISSUE THREAD

**Issue by krishnabhat3383** [GabLeRoux/macos-crossover-cloud-build#23]
Hi, I am new here and on Mac OS in general. I recently came across the following error towards the end of the script `build_local.sh`:
```
configure: error: C compiler cannot create executables
```
which directed me to check the config.log file, which I am attaching here forthwith.
[config.log](https://github.com/GabLeRoux/macos-crossover-cloud-build/files/6973550/config.log)

My guess is that Xcode/macOS doesn't allow unknown compilers to compile and create executables. Since this build is using it's own llvm and clang environment, could it be that Xcode doesn't like the same? Any help would be great. Me and my pals are very new to this new ecosystem we have adopted and would love some help/mentoring.

Thanks in advance.

**Comment by dasmy** [comment]
I briefly looked at the config.log. - Do you use an M1 Mac (I.e. an Arm processor instead of Intel)? As far as I know, we only tested on Intel hardware for now. Somewhere in the script, there is a configure setting for Clang, that restricts it to X86 targets. - Maybe, this is the problem?

@Gcenx, do you have any idea here? Can we build/test on M1 mac's somehow?

**Comment by Gcenx** [comment]
@dasmy I never tested building this project on my M1 Mac Mini, but it does need to be compiled under a Rosetta2 terminal session but we'll need to modify `build_local.sh` to detect and manually configure `$PATH` as most users lightly don't have a viable configuration for this.

So for building this project it requires running via Rosetta2 and an Intel brew install.

**Comment by krishnabhat3383** [comment]
so would running the script under `arch -x86_64` would help? since brew runs in the script, it would pick up on the architecture change and do the necessary, wouldn't it?

**Comment by Gcenx** [comment]
@krishnabhat3383 unfortunately that’s not the case for brew as they decided to keep with the single arch only setup meaning you still required an Intel brew install (/usr/local/) that’s in $PATH before the aarch64 copy (/opt/homebrew)

As I’m currently at work I can’t prove how I handle this on my own system but I basically have a different $PATH configuration when running native and another for a Rosetta2 session.

But to resolve this within the project would require forcing the entire script to run `arch -x86_64` and ignoring the users $PATH entirely to configure an expected working configuration.


A basic example `.zprofile`
```
if [ "$(sysctl -n sysctl.proc_translated)" = "1" ]; then
    local brew_path="/usr/local"
else
    local brew_path="/opt/homebrew"
fi

# Manually added standard $PATH at the end to avoid having /usr/local/bin in aarch64 $PATH
export PATH="${brew_path}/bin:${brew_path}/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin"
```

**Comment by Gcenx** [comment]
Should now be resolved via https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/commit/0f0a49ee48387d8327b9a4cd52a2c99bb6785fef
