### ISSUE TITLE
How to Run?

### ISSUE THREAD

**Issue by firefinchdev** [GabLeRoux/macos-crossover-cloud-build#24]
Possibly a noob question, but after "compiling" (as mentioned in `README.md` 🌚🌝),
how do I actually run it?
Should I just run `wine-cx/usr/local/bin/wine64 path/to/windows/program`?

If yes, then isn't it just wine? Where is crossover then?

Thanks.

**Comment by Gcenx** [comment]
You seem to be misunderstanding something, this project compiles the FOSS portion of CrossOver that CodeWeavers provide.

CodeWeavers don’t provide the sources for there GUI and some other components that are closed source, the _wine_ portion is provided and that’s what is project compiles.

**Comment by Gcenx** [comment]
@GabLeRoux might want to rename the project to avoid any more confusion.

Maybe something like `macos-crossover-wine-cloud-builder`

**Comment by GabLeRoux** [comment]
Yep, I just renamed from `macos-crossover-cloud-build` to `macos-crossover-wine-cloud-builder` 👍

Gcenx's right, the project allows you to download an already built version of `wine` for macos using github-actions so you can simply download the binaries, add them to your `$PATH` (or run it directly) and use them to launch windows apps on macOS :)

You can find the binaries built on github-actions in the `Artifacts`  section of [the succeeding jobs](https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/actions/)

## Here's a random example where I install and run [soldat game](https://soldat.pl/en/) 😆

1. Use latest successful build [(I used this one)](
https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/actions/runs/1120073712)

2. Download and unzip `wine-cx21.0.0.zip`:

![image](https://user-images.githubusercontent.com/1264761/135181923-af6cb0a6-4860-4a72-ac01-415858d01d67.png)

![image](https://user-images.githubusercontent.com/1264761/135181936-9cd732ba-715c-4253-9f15-549a18bf98f1.png)

3. Use wine to run the downloaded `.exe`:

```bash
cd ~/downloads/wine-cx21.0.0/
./usr/local/bin/wine64 ~/Downloads/soldat1711.exe
```
![image](https://user-images.githubusercontent.com/1264761/135182474-8351678d-b1bb-4caf-a542-72436aade600.png)

![image](https://user-images.githubusercontent.com/1264761/135182505-8aabbbad-d429-497a-9f5f-6d10fe460ac3.png)

![image](https://user-images.githubusercontent.com/1264761/135183369-2eb3bc41-ba75-4816-aa75-0b0702fc61d9.png)

4. You can then use Wine's explorer to launch installed things:

```bash
./usr/local/bin/wine64 explorer
```

![image](https://user-images.githubusercontent.com/1264761/135182595-4d34236c-5492-4a45-9714-857270793bc3.png)

🦾

**Comment by firefinchdev** [comment]
> You seem to be misunderstanding something, this project compiles the FOSS portion of CrossOver that CodeWeavers provide.
> 
> CodeWeavers don’t provide the sources for there GUI and some other components that are closed source, the _wine_ portion is provided and that’s what is project compiles.

My bad, I interpreted it wrongly...
Just to confirm, Crossover maintains a fork of [_wine_](https://www.winehq.org/), and due to licensing, they have to provide source for their own fork of _wine_.
Am I right?

**Comment by firefinchdev** [comment]
Also, Crossover has the concept of "Bottles". If we are using crossover wine, do we need that "bottle"?
If yes, any way to use those bottles from command line?
Thanks.

**Comment by Gcenx** [comment]
> Also, Crossover has the concept of "Bottles". If we are using crossover wine, do we need that "bottle"?

Replace "Bottle" with "Prefix" and you'd be more inline with upstream wine.

> If yes, any way to use those bottles from command line?

CrossOver stores it's "bottle" at `~/Library/Application\ Support/CrossOver/Bottles` to use one of those say "Steam" for example set;
```
export WINEPREFIX="/Users/$whoami/Library/Application Support/CrossOver/Bottles/Steam"
```
Now call `wine32on64` or `wine64` as usual.

**Comment by firefinchdev** [comment]
@Gcenx 
This solves all of my queries.
Thanks a lot :)

Should we keep this open? I think the above discussion is useful for users...

**Comment by Gcenx** [comment]
@firefinchdev I'm not entirely sure what’s the best course of action.

I guess explaining “Bottle” = “Prefix” and the location _where_ CrossOver saves it’s “Bottles” might be helpful but otherwise it’s all just wine knowledge.

@GabLeRoux did a little tweak to your comment as you can just call `wine64 explorer`

**Comment by firefinchdev** [comment]
Oh okay..
If its common knowledge, then we can close it...

**Comment by dasmy** [comment]
> Yep, I just renamed from `macos-crossover-cloud-build` to `macos-crossover-wine-cloud-builder` 👍
> 
> Gcenx's right, the project allows you to download an already built version of `wine` for macos using github-actions so you can simply download the binaries, add them to your `$PATH` (or run it directly) and use them to launch windows apps on macOS :)
> 
> You can find the binaries built on github-actions in the `Artifacts` section of [the succeeding jobs](https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/actions/)
> 
> ## Here's a random example where I install and run [soldat game](https://soldat.pl/en/) 😆
> 1. Use latest successful build [(I used this one)](https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/actions/runs/1120073712)
> 2. Download and unzip `wine-cx21.0.0.zip`:
> 
> ![image](https://user-images.githubusercontent.com/1264761/135181923-af6cb0a6-4860-4a72-ac01-415858d01d67.png)
> 
> ![image](https://user-images.githubusercontent.com/1264761/135181936-9cd732ba-715c-4253-9f15-549a18bf98f1.png)
> 
> 1. Use wine to run the downloaded `.exe`:
> 
> ```shell
> cd ~/downloads/wine-cx21.0.0/
> ./usr/local/bin/wine64 ~/Downloads/soldat1711.exe
> ```
> 
> ![image](https://user-images.githubusercontent.com/1264761/135182474-8351678d-b1bb-4caf-a542-72436aade600.png)
> 
> ![image](https://user-images.githubusercontent.com/1264761/135182505-8aabbbad-d429-497a-9f5f-6d10fe460ac3.png)
> 
> ![image](https://user-images.githubusercontent.com/1264761/135183369-2eb3bc41-ba75-4816-aa75-0b0702fc61d9.png)
> 
> 1. You can then use Wine's explorer to launch installed things:
> 
> ```shell
> ./usr/local/bin/wine64 explorer
> ```
> 
> ![image](https://user-images.githubusercontent.com/1264761/135182595-4d34236c-5492-4a45-9714-857270793bc3.png)
> 
> 🦾

@GabLeRoux maybe, it makes sense to add something similar to this and also answers to the questions of @firefinchdev to Readme.md ? - These hints might be very helpful for others as well...

**Comment by Gcenx** [comment]
@dasmy my view is to only provide some basic information like “Bottle” = “Wineprefix” etc.

As @GabLeRoux seems to be in favor of providing “releases” so that would avoid some additional confusion.

After these two it’s a matter of how much duplication is desirable?, maybe adding some links to Winehq macOS wiki etc

**Comment by Gcenx** [comment]
Making another comment instead of editing the above so everyone see it.

If the Winehq macOS wiki is lacking or something would make sense written another way just message me with the desired changes and I can update the information.

Currently working on gstreamer1 plugins to hopefully drop winequicktime decoder since that’s useless at this point, the plan is to eventually rework the Winehq macOS wiki sections so any help on that would be appreciated.
