### ISSUE TITLE
Unable to compile locally on Apple Silicon

### ISSUE THREAD

**Issue by lbibass** [GabLeRoux/macos-crossover-cloud-build#30]
Hi, trying to compile this locally on my Apple Silicon machine. I'm using the ./build_local script. 

```
error: unable to create target: 'No available targets are compatible with triple "armv4t-apple-macosx10.14.0"'
```

This error happens when I try and compile wine64. Any ideas?

**Comment by Gcenx** [comment]
The script must be ran via Rosetta2 that’s why it’s failing for you.

**Comment by Gcenx** [comment]
Should now be resolved via https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/commit/0f0a49ee48387d8327b9a4cd52a2c99bb6785fef
