### ISSUE TITLE
Keep project self-contained or use third-party packages?

### ISSUE THREAD

**Issue by Gcenx** [GabLeRoux/macos-crossover-cloud-build#35]
This topic always come to mind for obvious reasons, usually leaning on the side of caution keeping projects more self contained.

@GabLeRoux & @dasmy what are your thoughts on this?, should this be kept self-contained or take advantage of external projects offerings.

**Comment by dasmy** [comment]
I'd really go for self-containedness as much as possible in two aspects:
* Considering the recent issues with update tools in homebrew, I was already thinking wether it wouldn't be preferable to build all (!) required stuff on our own
* Looking at release distribution, having a fully self-contained package, I.e. without the need to install components using brew on the user side, would be very desirable as well (see also https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/issues/25#issuecomment-1088583810)

Still, these would be much work (too much, I guess).

In another direction, we could also think about some non-self-containedness by e.g. including some more recent DXVK / MoltenVK packages than those provided in the original tarball if this is of any use. - Clearly, I am no expert in these, though 😎

**Comment by Gcenx** [comment]
The only thing that’s currently been causing us breakages is bumping of mingw-gcc components so maybe it would be a good idea to make a completely isolated formula for this to avoid any possible breakages.

Distribution would require all needed runtime libraries to be bundled or it would become broken very quickly.

DXVK, this really depends as everyone’s packages bar mine require a modified version of MoltenVK to function. The problem with modified MoltenVK is some apps will launch assuming these faked functions exist causing a hard lock or a crash.

MoltenVK, already explained above except that currently v1.1.9 is rathe broken for DXVK usage hopefully this gets resolved, meaning v1.1.8 is currently the best version for DXVK usage.

**Comment by Gcenx** [comment]
With stock MoltenVK some env options would need to be provided for now

```
MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE= 1 // XXX Required by DXVK for AMD500/Intel GPUs
MVK_ALLOW_METAL_FENCES= 1 // XXX Required by DXVK for Apple/NVidia GPUs (better FPS than CPU Emulation)
MVK_CONFIG_RESUME_LOST_DEVICE= 1 // XXX Required by WINE (doesn't handle VK_ERROR_DEVICE_LOST correctly)
```

But at least there’s no need to fake Vulkan extensions, now windows apps that require say geometry shader simply won’t function.

**Comment by Gcenx** [comment]
@dasmy starting to think we remove llvm/clang stage entirely I can add a macOS Mojave bottle for cx-llvm then we’re good for macOS Catalina and above for that at least and saves a good few hours of compile time.

MoltenVK-CX seems redundant as with a couple of env options and some simple tweaks to DXVK sources it runs on stock MoltenVK see https://github.com/Gcenx/DXVK-macOS/tree/v1.10.1-macOS-min-patches

Removing the above means being able to just focus on keeping winecx building.
