### ISSUE TITLE
DXVK stage broken (mingw-w64 bump)

### ISSUE THREAD

**Issue by Gcenx** [GabLeRoux/macos-crossover-cloud-build#36]
This breakage may have been caused by the recent gcc12.1 bump not sure.

**Comment by dasmy** [comment]
Might be solvable by adding "`-include <utility>`" to CPPFLAGS 

I can't test atm - currently on vacation 😊

**Comment by Gcenx** [comment]
Yeah this breakage was caused by the gcc12 bump sigh…

> Might be solvable by adding "`-include <utility>`" to CPPFLAGS

Not sure about adding that via CPPFLAGS it would be better to patch the sources like we’ve done prior for the mingw changes.

> I can't test atm - currently on vacation 😊

Enjoy your vacation 😁

**Comment by Gcenx** [comment]
Sigh, ether the first patch apply and the second fails or the second applies and the first fails….

Guess those need to be combined into a single patch….

**Comment by Gcenx** [comment]
[0002-fixes-for-mingw-gcc-12.patch.zip](https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/files/8712444/0002-fixes-for-mingw-gcc-12.patch.zip)

The following patch fixes the build issues, I did try but ugh actions was being insufferable
