### ISSUE TITLE
configure: error: Your bison version is too old. Please install bison version 3.0 or newer.

### ISSUE THREAD

**Issue by GabLeRoux** [GabLeRoux/macos-crossover-cloud-build#4]
As seen here:  
https://github.com/GabLeRoux/macos-crossover-cloud-build/runs/1589360065

After a 3h build, it fails because `bison` is too old 🔥

**Comment by Gcenx** [comment]
Brew no longer allows force linking system provided packages, just change the export as I’d explained in the closed pull-request.

Also build llvm/clang using ninja set the max possible threads to be used then llvm/clang should compile in under one hour on a crappy system

**Comment by GabLeRoux** [comment]
Yeah I just saw that. I fixed `bison`'s export path, it was missing `/bin` at the end. Your related message: https://github.com/GabLeRoux/macos-crossover-cloud-build/pull/3#issuecomment-749112402 <3

```bash
export PATH="$(brew --prefix bison)/bin:$PATH"
```

```bash
bison --version
```
```
bison (GNU Bison) 3.7.4
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Thanks 👍

**Comment by TIOUAL** [comment]
Hi Guys !
@GabLeRoux @Gcenx , i'm using Centos7 and i have some error to install wine and i need you to help me to fix this error, but i'm not understund all your discussions :), can you expalin me step by step  what i can do plesae ?
Thank you so much,
Mohamed

**Comment by Gcenx** [comment]
@TIOUAL the provided builder is setup for building crossover-sources for macOS not Linux.

On Linux you’d be best to use your distro provided wine packages/Proton/GE-Proton/Wine-GE
