### ISSUE TITLE
xattr -r is not recognized 

### ISSUE THREAD

**Issue by nmcc1212** [GabLeRoux/macos-crossover-cloud-build#48]
on ventura, i am getting this error when running `sudo xattr -r -d com.apple.quarantine wine-cx21.2.0`

<img width="792" alt="image" src="https://user-images.githubusercontent.com/48334675/223700583-139b4bba-65c3-491d-bbf5-bf3f2d825ca3.png">

**Comment by nmcc1212** [comment]
my xattr was not the mac one it was the python one (/Library/Frameworks/Python.framework/Versions/3.10/bin/xattr) should be (/usr/bin/xattr)

**Comment by Gcenx** [comment]
Did you manually add `/Library/Frameworks/Python.framework/Versions/3.10/bin/` into `$PATH`?

I’ve seen this issue been reported on one of my own projects also but I’ve not seen this issue on my own m1 Mac mini running macOS Ventura 13.2.1

**Comment by nmcc1212** [comment]
There is nothing in my `.zshrc` that references that path, i dont know what program is adding it to path, maybe homebrew?
