### ISSUE TITLE
distversion.h has the wrong contents

### ISSUE THREAD

**Issue by Gcenx** [GabLeRoux/macos-crossover-cloud-build#7]
https://github.com/GabLeRoux/macos-crossover-cloud-build/blob/f1c67f1321cb23568e5ee94d8e4d40ba1b63c232/distversion.h#L1

Correcting this would resolve at least one of the issues your seeing.

**Comment by GabLeRoux** [comment]
Thanks, updated the content using the gist. Nice catch 👍
